
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg.SkillModule;

import luban.*;


public final class SchoolSkill extends AbstractBean {
    public SchoolSkill(ByteBuf _buf) { 
        id = _buf.readInt();
        name = _buf.readString();
        icon = _buf.readInt();
        funcdesc = _buf.readString();
        rolecreatedesc = _buf.readString();
    }

    public static SchoolSkill deserialize(ByteBuf _buf) {
            return new cfg.SkillModule.SchoolSkill(_buf);
    }

    /**
     * 门派技能编号
     */
    public final int id;
    /**
     * 技能名字
     */
    public final String name;
    /**
     * 技能图标
     */
    public final int icon;
    /**
     * 功效描述
     */
    public final String funcdesc;
    /**
     * 创建角色使用的功效描述
     */
    public final String rolecreatedesc;

    public static final int __ID__ = -1380575572;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "(format_field_name __code_style field.name):" + id + ","
        + "(format_field_name __code_style field.name):" + name + ","
        + "(format_field_name __code_style field.name):" + icon + ","
        + "(format_field_name __code_style field.name):" + funcdesc + ","
        + "(format_field_name __code_style field.name):" + rolecreatedesc + ","
        + "}";
    }
}

