
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg.SkillModule;

import luban.*;


public final class TbSchoolSkill {
    private final java.util.HashMap<Integer, cfg.SkillModule.SchoolSkill> _dataMap;
    private final java.util.ArrayList<cfg.SkillModule.SchoolSkill> _dataList;
    
    public TbSchoolSkill(ByteBuf _buf) {
        _dataMap = new java.util.HashMap<Integer, cfg.SkillModule.SchoolSkill>();
        _dataList = new java.util.ArrayList<cfg.SkillModule.SchoolSkill>();
        
        for(int n = _buf.readSize() ; n > 0 ; --n) {
            cfg.SkillModule.SchoolSkill _v;
            _v = cfg.SkillModule.SchoolSkill.deserialize(_buf);
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.HashMap<Integer, cfg.SkillModule.SchoolSkill> getDataMap() { return _dataMap; }
    public java.util.ArrayList<cfg.SkillModule.SchoolSkill> getDataList() { return _dataList; }

    public cfg.SkillModule.SchoolSkill get(int key) { return _dataMap.get(key); }

}
