
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg.SystemModule;

public final class ERace {
    /**
     * 人族
     */
    public static final int Human = 0;
    /**
     * 仙族
     */
    public static final int Celestial = 1;
    /**
     * 妖族
     */
    public static final int Demon = 2;
}

