
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg.SystemModule;

public final class ESchoolType {
    /**
     * 蜀山
     */
    public static final int ShuMountain = 0;
    /**
     * 金山寺
     */
    public static final int GoldenMountainTemple = 1;
    /**
     * 太初
     */
    public static final int TaiChu = 2;
    /**
     * 瑶池
     */
    public static final int Yaochi = 3;
    /**
     * 青城
     */
    public static final int Qingcheng = 4;
    /**
     * 妖神宫
     */
    public static final int DemonGodPalace = 5;
}

