
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg.SystemModule;

import luban.*;


public final class School extends AbstractBean {
    public School(ByteBuf _buf) { 
        SchoolType = _buf.readInt();
        Name = _buf.readString();
        Desc = _buf.readString();
        IconPath = _buf.readString();
        HighligtedIconPath = _buf.readString();
        NamePath = _buf.readString();
        Characteristic = _buf.readString();
        {int n = Math.min(_buf.readSize(), _buf.size());SkillList = new java.util.ArrayList<Integer>(n);for(int i = 0 ; i < n ; i++) { Integer _e;  _e = _buf.readInt(); SkillList.add(_e);}}
    }

    public static School deserialize(ByteBuf _buf) {
            return new cfg.SystemModule.School(_buf);
    }

    /**
     * 门派类型
     */
    public final int SchoolType;
    /**
     * 门派名字
     */
    public final String Name;
    /**
     * 描述
     */
    public final String Desc;
    /**
     * 图标
     */
    public final String IconPath;
    /**
     * 图标高亮
     */
    public final String HighligtedIconPath;
    /**
     * 名称
     */
    public final String NamePath;
    /**
     * 门派特色描述路径
     */
    public final String Characteristic;
    /**
     * 创角显示的技能列表
     */
    public final java.util.ArrayList<Integer> SkillList;

    public static final int __ID__ = 675888967;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "(format_field_name __code_style field.name):" + SchoolType + ","
        + "(format_field_name __code_style field.name):" + Name + ","
        + "(format_field_name __code_style field.name):" + Desc + ","
        + "(format_field_name __code_style field.name):" + IconPath + ","
        + "(format_field_name __code_style field.name):" + HighligtedIconPath + ","
        + "(format_field_name __code_style field.name):" + NamePath + ","
        + "(format_field_name __code_style field.name):" + Characteristic + ","
        + "(format_field_name __code_style field.name):" + SkillList + ","
        + "}";
    }
}

