
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import luban.*;

public final class Tables
{
    public  static interface  IByteBufLoader {
        ByteBuf load(String file) throws java.io.IOException;
    }

    private final cfg.SkillModule.TbSchoolSkill _tbschoolskill;
    public cfg.SkillModule.TbSchoolSkill getTbSchoolSkill() { return _tbschoolskill; }
    private final cfg.SystemModule.TbRoleType _tbroletype;
    public cfg.SystemModule.TbRoleType getTbRoleType() { return _tbroletype; }
    private final cfg.SystemModule.TbSchool _tbschool;
    public cfg.SystemModule.TbSchool getTbSchool() { return _tbschool; }

    public Tables(IByteBufLoader loader) throws java.io.IOException {
        _tbschoolskill = new cfg.SkillModule.TbSchoolSkill(loader.load("skillmodule_tbschoolskill")); 
        _tbroletype = new cfg.SystemModule.TbRoleType(loader.load("systemmodule_tbroletype")); 
        _tbschool = new cfg.SystemModule.TbSchool(loader.load("systemmodule_tbschool")); 
    }
}

